---

AllCops:
  Exclude:
    - bundle/**/*
  TargetRubyVersion: 2.7

Metrics/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Security/Eval:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*

Style/AsciiComments:
  Enabled: false
